name: Multi Platform Runner 
defaults:
  run:
    shell: bash -ieo pipefail {0}
on: 
  workflow_dispatch:

jobs:
  integration-tests:
    strategy:
      matrix:
        project: [hello-spring]
        java: [8]
        jbang: [0.84.2]
        java-buildpack-lib-sha: [FISH]
        runner: [ macos-15-large,ubuntu-24.04 ]
    runs-on: [ "${{ matrix.runner }}" ]
    name: Test Java ${{ matrix.java }} JBang ${{ matrix.jbang }} Project ${{ matrix.project }} Runner ${{ matrix.runner }}
    steps:
      - name: Podman Mac
        if: matrix.runner == 'macos-15-large'
        run: |
          echo "Doing the thing for macos"
          cd /tmp
          wget -nv "https://github.com/containers/podman/releases/download/v5.3.1/podman-installer-macos-universal.pkg"
          sudo installer -pkg /tmp/podman-installer-macos-universal.pkg -target /
          export PATH=$PATH:/opt/podman/bin
          podman --log-level=debug machine init
          podman --log-level=debug machine start
          
      - name: Podman Ubuntu
        if: matrix.runner == 'ubuntu-24.04'
        run: |
          echo "Doing the thing for ubuntu" 

      - name: Podman info
        run: |
          podman info
          
      - name: Drive test
        run: |
          echo Setting up to run ${{ matrix.project }} with ${{ matrix.java-buildpack-lib-sha }} on ${{ matrix.runner }}
          export CURRENT_WORKFLOW_DEP=com.github.BarDweller.java-buildpack-client:buildpack-client:${{ matrix.java-buildpack-lib-sha }}
          export PROJECT_PATH=./test-projects/${{ matrix.project }}
          echo TEST $CURRENT_WORKFLOW_DEP $PROJECT_PATH
