name: Debug
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dump info
        run: |
          #echo ETC DUMP
          #ls -al /etc
          echo VAR RUN USER DUMP
          ls -al /run/user/`id -u`
          #echo VAR RUN 
          #ls -al /var/run
          echo RUN PODMAN
          ls -al /run/podman
          echo PODMAN VERSION
          podman --version
          echo DOCKER_HOST
          echo ${DOCKER_HOST}
          echo PODMAN PS
          podman ps -a
          echo PODMAN LIST IMAGES
          podman images list
          echo PODMAN INFO
          podman info
