jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dump info
        run: |
          ls -al /etc
          ls -al /var/run/user/1000/podman
          ls -al /var/run/*.sock
          podman --version
          echo Docker-Host ${DOCKER_HOST}
