name: Debug
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dump info
        run: |
          echo ETC DUMP
          ls -al /etc
          echo VAR RUN USER DUMP
          ls -al /var/run/user/`id -u`/podman
          echo VAR RUN SOCK 
          ls -al /var/run/*.sock
          echo PODMAN VERSION
          podman --version
          echo DOCKER_HOST
          echo ${DOCKER_HOST}
